
services:
  psql:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supplier
    ports:
      - "5432:5432"
  supplier:
      build: ./supplier
      ports:
      - "8080:8080"
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
        interval: 30s
        timeout: 10s
        retries: 3

      depends_on:
        psql:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/supplier
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
  consumer:
      build: ./consumer
      ports:
      - "8081:8080"

      depends_on:
        supplier:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/supplier
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres